# Generated by Django 3.2.3 on 2021-05-27 09:15

from django.db import migrations
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.AlterField(
            model_name='place',
            name='geolocation',
            field=geolocation_fields.models.fields.PointField(verbose_name='field_name'),
        ),
    ]
