# Generated by Django 3.2.3 on 2021-05-27 09:40

from django.db import migrations, models
import django_countries.fields
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20210527_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='country',
            field=django_countries.fields.CountryField(default='TR', max_length=2),
        ),
        migrations.AlterField(
            model_name='place',
            name='geolocation',
            field=geolocation_fields.models.fields.PointField(verbose_name='Marker'),
        ),
    ]
