# Generated by Django 3.2.3 on 2021-09-06 07:01

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('kd', 'Karadeniz Yöresi'), ('ad', 'Anadolu Yöresi'), ('mr', 'Marmara Yöresi'), ('eg', 'Ege Yöresi')], max_length=3)),
                ('music_name', models.CharField(max_length=200)),
                ('url', models.FileField(upload_to='musics', validators=[media.models.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('url', models.FileField(upload_to='videos', validators=[media.models.validate_file_extension])),
            ],
        ),
    ]
