# Generated by Django 3.2.3 on 2021-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_name',
            new_name='place',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='sad', upload_to='media/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='dsf', upload_to='media/videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='videos'),
        ),
    ]
