# Generated by Django 3.2.3 on 2021-09-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='singer_name',
            field=models.CharField(default='Azad', max_length=200),
            preserve_default=False,
        ),
    ]
